"""messages to message

Revision ID: 96b6c04e138f
Revises: 
Create Date: 2025-06-08 11:50:11.007610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b6c04e138f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=2000), nullable=False))
        batch_op.drop_column('messages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.VARCHAR(length=2000), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
